#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Inicia el usuario systemd (si no está ya)
systemctl --user import-environment PATH DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR

# VARIABLES
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export GTK_THEME=Juno-ocean
export XCURSOR_THEME=miniature
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=qt5ct

export BROWSER=firefox
export TERMINAL=kitty
export EDITOR=nvim
export FILE_MANAGER=yazi
export IMAGE=nsxiv
export VIDEO=mpv
#export XCURSOR_SIZE=24

# Keyboard layout
riverctl keyboard-layout latam

# AUTOSTART
sh $HOME/.config/scripts/autostart-wayland.sh &

# HOTKEYS

# Super+Space to start an instance of kitty
riverctl map normal Super Space spawn kitty

# Super+Space to start wofi
riverctl map normal Super A spawn "env QT_QPA_PLATFORMTHEME=qt5ct QT_STYLE_OVERRIDE=qt5ct GTK_THEME=Juno-ocean wofi --show drun"
#riverctl map normal Super A spawn "wofi --show drun"

# Super+Shift+Space to start an instance of yazi
riverctl map normal Super+Shift Space spawn "kitty yazi"

# Super+W to close the focused view
riverctl map normal Super W close

# Super+Control+B to Show/hide the bar
riverctl map normal Super+Control B spawn "yambar &"

# Super+Control+Q to exit river
riverctl map normal Super+Control Q exit

# Super+Control+R to reload config file
riverctl map normal Super+Control R spawn "$HOME/.config/river/init"
#
# # Super+Control+F to fix suspend issues
# riverctl map normal Super+Control F spawn "$HOME/.config/scripts/fix-suspend.sh"

# Change layout distribution
riverctl map normal Super D spawn "$HOME/.config/scripts/keyboard-lang.sh"

# Power menu
riverctl map normal Super P spawn "$HOME/.config/scripts/powermenu-wofi.sh"

# screenpad
riverctl map normal Super+Alt 8 spawn "$HOME/.config/scripts/screenpad.sh"

# mirror screen
riverctl map normal Super+Alt 9 spawn "$HOME/.config/scripts/mirror-wofi.sh"

# Wallpaper selector
riverctl map normal Super+Alt 0 spawn "$HOME/.config/scripts/wallpaper-wofi.sh"

# Wifi menu
riverctl map normal Super N spawn "kitty nmtui"

# Screenshot
riverctl map normal Super S spawn "$HOME/.config/scripts/screenshot-wofi.sh"
# Uncomment the following line if you prefer rofi for screenshots
# riverctl map normal Super S spawn "$HOME/.config/scripts/screenshot-rofi.sh"

# Clipboard
riverctl map normal Super V spawn "$HOME/.config/scripts/rofi-gpaste.sh"

# Calculator launcher
riverctl map normal Super C spawn "kitty fend" #"wofi -show calc -modi calc -no-show-match -no-sort"

# Browser
riverctl map normal Super E spawn "librewolf"

# Mount
riverctl map normal Super U spawn "$HOME/.config/scripts/usbmounter.sh -r"

# Unmount
riverctl map normal Super M spawn "$HOME/.config/scripts/usbmounter.sh -r -m"


# Multimedia keys

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 4'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 4'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done


# Increase brightness
riverctl map normal XF86MonBrightnessUp spawn "brightnessctl set +4%"

# Decrease brightness
riverctl map normal XF86MonBrightnessDown spawn "brightnessctl set 4%-"

# Touchpad events
for pad in $(riverctl list-inputs | grep -i touchpad )
do
    riverctl input $pad events enabled
    riverctl input $pad tap enabled
    riverctl input $pad disable-while-typing enabled
    riverctl input $pad scroll-method two-finger
    riverctl input $pad tap-button-map left-right-middle
    riverctl input $pad scroll-factor 0.8
done

riverctl focus-follows-cursor always


# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# wideriver
# riverctl map normal Super up send-layout-cmd wideriver "--layout up"
riverctl map normal Super down send-layout-cmd wideriver "--layout wide"
riverctl map normal Super left send-layout-cmd wideriver "--layout left"
riverctl map normal Super right send-layout-cmd wideriver "--layout right"

riverctl map normal Super Tab send-layout-cmd wideriver "--layout-toggle"
# Super + Middle to layout toggle
riverctl map-pointer normal Super BTN_MIDDLE send-layout-cmd wideriver "--layout-toggle"

riverctl map normal Super l send-layout-cmd wideriver "--ratio +0.025"
riverctl map normal Super minus send-layout-cmd wideriver "--ratio 0.50"
riverctl map normal Super h send-layout-cmd wideriver "--ratio -0.025"

riverctl map normal Super+Shift l send-layout-cmd wideriver "--count +1"
riverctl map normal Super+Shift minus send-layout-cmd wideriver "--count 1"
riverctl map normal Super+Shift h send-layout-cmd wideriver "--count -1"

riverctl map normal Super+Shift up send-layout-cmd wideriver "--layout monocle"
riverctl map normal Super+Shift left send-layout-cmd wideriver "--stack dwindle --count 1 --ratio 0.5"
riverctl map normal Super+Shift right send-layout-cmd wideriver "--stack even --count 2 --ratio 0.55"
riverctl map normal Super+Shift down send-layout-cmd wideriver "--stack diminish --count 3 --ratio 0.4"

# # rivertile
#
# # Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
# riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
# riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
#
# # Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"
#
# # Super+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal Super+Control k send-layout-cmd rivertile "main-location top"
# riverctl map normal Super+Control l send-layout-cmd rivertile "main-location right"
# riverctl map normal Super+Control j send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super+Control h send-layout-cmd rivertile "main-location left"

# # rivertile original
#
# # Super+Alt+{H,J,K,L} to move views
# riverctl map normal Super+Alt H move left 100
# riverctl map normal Super+Alt J move down 100
# riverctl map normal Super+Alt K move up 100
# riverctl map normal Super+Alt L move right 100
#
# # Super+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Super+Alt+Control H snap left
# riverctl map normal Super+Alt+Control J snap down
# riverctl map normal Super+Alt+Control K snap up
# riverctl map normal Super+Alt+Control L snap right
#
# # Super+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal Super+Alt+Shift H resize horizontal -100
# riverctl map normal Super+Alt+Shift J resize vertical 100
# riverctl map normal Super+Alt+Shift K resize vertical -100
# riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# # Super + Middle Mouse Button to toggle float
# riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [1-9]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag and also focus view tag [1-9]
    riverctl map normal Super+Shift $i spawn "riverctl set-view-tags $tags; riverctl set-focused-tags $tags"

    # Super+Control+[1-9] to tag focused view with tag [1-9]
    riverctl map normal Super+Control $i set-view-tags $tags

    ## Super+Shift+[1-9] to tag focused view with tag [1-9]
    #riverctl map normal Super+Shift $i set-view-tags $tags

    ## Super+Control+[1-9] to toggle focus of tag [1-9]
    #riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [1-9] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 9) - 1))
#all_tags=$(((1 << 32) - 1))

# Super+0 to focus all tags
riverctl map normal Super 0 set-focused-tags $all_tags

# Super+Shift+0 to tag focused view with all tags
riverctl map normal Super+Shift t set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super T toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Set background and border color
riverctl background-color 0x000000
riverctl border-color-focused 0x6E7C99
riverctl border-color-unfocused 0x1C1F26

# Set keyboard repeat rate
riverctl set-repeat 50 300

# CONFIGURE MISELANIUS

# Make all views with an app-id that starts with "float" start floating.
riverctl rule-add -app-id "float*" float
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Make all views with an app-id that starts with "float" and title "foo" start floating.
#riverctl rule-add -app-id "float*" -title "foo" float

# Set app-ids of views which should use server side decorations
riverctl rule-add -app-id "firefox" ssd 
riverctl rule-add -app-id "leafpad" ssd
riverctl rule-add -app-id "mousepad" ssd
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" ssd

# Bar
riverctl spawn yambar
#riverctl spawn i3bar-river

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
#riverctl default-layout rivertile
#rivertile -view-padding 0 -outer-padding 0 &

# Set the default layout generator to be the one that you select and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl rule-add ssd
riverctl default-layout wideriver
# start layout manager
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --no-smart-gaps                            \
    --inner-gaps                   0           \
    --outer-gaps                   0           \
    --border-width                 1           \
    --border-width-monocle         0           \
    --border-width-smart-gaps      0           \
    --border-color-focused         "0x6E7C99"  \
    --border-color-focused-monocle "0x586e75"  \
    --border-color-unfocused       "0x1C1F26"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

	
